/**
 * Created by Adonis on 8/22/2014.
 */


var resource = {
    game_background : 'res/image/background_fix.png',
    game_ground : 'res/image/ground.png',
    game_plane : 'res/image/plane.png',
    game_helicoptor : 'res/image/helicoptor.png',
    game_plane_sel : 'res/image/plane_selected.png',
    game_helicoptor_sel : 'res/image/helicoptor_selected.png',
    game_character_plane_1 : 'res/image/character_plane_1.png',
    game_character_plane_2 : 'res/image/character_plane_2.png',
    game_character_helicoptor_1 : 'res/image/character_helicopter_1.png',
    game_character_helicoptor_2 : 'res/image/character_helicopter_2.png',
    game_obstacle_buildingOne : 'res/image/building_one.png',
    game_obstacle_buildingTwo : 'res/image/building_two.png',
    game_obstacle_buildingThird : 'res/image/building_third.png',
    game_obstacle_buildingFour : 'res/image/building_four.png',
    game_obstacle_buildingFive : 'res/image/building_five.png',
    game_obstacle_flagTable : 'res/image/flag_table.png',
    game_obstacle_flag : 'res/image/flag.png',
    game_obstacle_cloudOne : 'res/image/cloud_one.png',
    game_obstacle_cloudTwo : 'res/image/cloud_two.png',
    game_obstacle_cloudThird : 'res/image/cloud_third.png',
    game_obstacle_cloudFour : 'res/image/cloud_four.png',
    game_obstacle_cloudFive : 'res/image/cloud_five.png',
    game_menu_select_nl : 'res/image/btn_menu_normal.png',
    game_menu_select_pr : 'res/image/btn_menu_pressed.png',
    game_replay_nl : 'res/image/btn_play_end_normal.png',
    game_replay_pr : 'res/image/btn_play_end_pressed.png',
    game_over_title : 'res/image/gameover_score.png',
    game_title : 'res/image/game_title.png',
    game_golden_sack : 'res/image/golden_sack.png',
    game_green_sack : 'res/image/green_sack.png',
    game_sack_board : 'res/image/sack_score_board.png',
    game_roadsignboard : 'res/image/roadsignboard.png',
    game_setSoundEna_nl : 'res/image/main_btn_soundon_nl.png',
    game_setSoundEna_st : 'res/image/main_btn_soundon_st.png',
    game_setSoundDis_nl : 'res/image/main_btn_soundoff_nl.png',
    game_setSoundDis_st : 'res/image/main_btn_soundoff_st.png',
    game_bg_music : 'res/audio/bg.mp3',
    game_click_music : 'res/effect/click.mp3',
    game_hit_music : 'res/effect/sfx_hit.mp3',
    game_hit_ground_music : 'res/effect/sfx_hit_ground.mp3',
    game_wing_music : 'res/effect/sfx_wing.mp3'
};

var g_resource = [
    resource.game_background,
    resource.game_ground,
    resource.game_plane,
    resource.game_helicoptor,
    resource.game_plane_sel,
    resource.game_helicoptor_sel,
    resource.game_character_plane_1,
    resource.game_character_plane_2,
    resource.game_character_helicoptor_1,
    resource.game_character_helicoptor_2,
    resource.game_obstacle_buildingOne,
    resource.game_obstacle_buildingTwo,
    resource.game_obstacle_buildingThird,
    resource.game_obstacle_buildingFour,
    resource.game_obstacle_buildingFive,
    resource.game_obstacle_flag,
    resource.game_obstacle_flagTable,
    resource.game_obstacle_cloudOne,
    resource.game_obstacle_cloudTwo,
    resource.game_obstacle_cloudThird,
    resource.game_obstacle_cloudFour,
    resource.game_obstacle_cloudFive,
    resource.game_menu_select_nl,
    resource.game_menu_select_pr,
    resource.game_replay_nl,
    resource.game_replay_pr,
    resource.game_over_title,
    resource.game_golden_sack,
    resource.game_green_sack,
    resource.game_sack_board,
    resource.game_roadsignboard,
    resource.game_title,
    resource.game_setSoundEna_nl,
    resource.game_setSoundEna_st,
    resource.game_setSoundDis_nl,
    resource.game_setSoundDis_st,
    resource.game_bg_music,
    resource.game_click_music,
    resource.game_hit_music,
    resource.game_hit_ground_music,
    resource.game_wing_music
];